from investment_assistant.safety import evaluate_retrieval


def test_retrieval_evaluation_detects_irrelevant_page_by_expected_keywords():
    sources = [{"content": "Total shareholders equity", "metadata": {"source_type": "pdf", "page": "35"}}]
    result = evaluate_retrieval("自由现金流是多少", sources, ["Cash generated by operating activities", "111,482"])
    assert not result["passed"]
    assert result["expected_source_recall"] == 0.0
    assert "预期证据未全部召回。" in result["findings"]


def test_workflow_retrieval_passes_ticker_and_discloses_no_local_material(monkeypatch):
    from investment_assistant import workflow

    class FakeRAG:
        def search(self, query, limit, ticker=None):
            assert ticker == "600519.SS"
            return []

        def local_document_count(self, ticker):
            assert ticker == "600519.SS"
            return 0

        def retrieval_status(self):
            return {"embedding_mode": "hash"}

    monkeypatch.setattr(workflow, "LocalResearchRAG", FakeRAG)
    state = {"ticker": "600519.SS", "topic": "\u73b0\u91d1\u6d41\u4e0e\u4f30\u503c", "horizon": "\u4e2d\u671f"}

    result = workflow.retrieve_evidence(state)

    assert result["sources"] == []
    assert not result["local_material_available"]
    assert result["retrieval_evaluation"]["findings"] == ["\u8be5\u6807\u7684\u65e0\u672c\u5730\u7814\u7a76\u8d44\u6599\uff1a600519.SS\u3002"]


def test_report_discloses_missing_local_material_and_excludes_other_ticker_documents():
    from investment_assistant.workflow import generate_report

    state = {
        "ticker": "600519.SS",
        "topic": "\u73b0\u91d1\u6d41\u4e0e\u4f30\u503c",
        "horizon": "\u4e2d\u671f",
        "created_at": "2026-09-08T00:00:00+00:00",
        "market_snapshot": {"data_available": False},
        "financial_snapshot": {"data_available": False},
        "market_model": {"state": "\u6570\u636e\u4e0d\u53ef\u7528", "risk_level": "\u672a\u77e5"},
        "sources": [
            {
                "citation": "S1",
                "metadata": {
                    "source_type": "news",
                    "ticker": "600519.SS",
                    "title": "\u5b9e\u65f6\u65b0\u95fb",
                    "source": "\u6d4b\u8bd5\u65b0\u95fb\u6e90",
                    "published_at": "2026-09-08",
                    "url": "https://example.com/news",
                },
            }
        ],
        "scenarios": [],
        "llm_result": {"used": False, "reason": "\u6d4b\u8bd5"},
        "local_material_available": False,
    }

    report = generate_report(state)["report"]

    assert "\u8be5\u6807\u7684\u65e0\u672c\u5730\u7814\u7a76\u8d44\u6599\uff1a600519.SS" in report
    assert "Apple_2025_Form_10-K.pdf" not in report

