from pathlib import Path

from pypdf import PdfWriter

from investment_assistant.rag import LocalResearchRAG, expand_financial_query, infer_ticker_from_filename
from investment_assistant.safety import evaluate_retrieval


class FakePage:
    def extract_text(self, **kwargs):
        assert kwargs["extraction_mode"] == "layout"
        return "本页披露：自由现金流保持为正。"


class FakeReader:
    is_encrypted = False
    pages = [FakePage()]


def test_pdf_index_skips_blank_pages_without_creating_evidence(tmp_path: Path):
    pdf_path = tmp_path / "blank.pdf"
    writer = PdfWriter()
    writer.add_blank_page(width=595, height=842)
    with pdf_path.open("wb") as file:
        writer.write(file)

    rag = LocalResearchRAG(path=tmp_path / "chroma")
    assert rag.index_pdf(pdf_path) == 0


def test_pdf_index_preserves_page_metadata(tmp_path: Path, monkeypatch):
    pdf_path = tmp_path / "annual_report.pdf"
    pdf_path.write_bytes(b"placeholder")
    monkeypatch.setattr("investment_assistant.rag.PdfReader", lambda _: FakeReader())
    rag = LocalResearchRAG(path=tmp_path / "chroma")
    assert rag.index_pdf(pdf_path) == 1
    source = rag.search("自由现金流", limit=1)[0]
    assert source["metadata"]["source_type"] == "pdf"
    assert source["metadata"]["page"] == "1"
    assert source["metadata"]["file_name"] == "annual_report.pdf"


def test_retrieval_evaluation_requires_pdf_page_number():
    sources = [{"content": "free cash flow", "metadata": {"source_type": "pdf", "page": ""}}]
    result = evaluate_retrieval("free cash flow", sources)
    assert not result["passed"]
    assert result["page_citation_coverage"] == 0.0


def test_retrieval_evaluation_measures_expected_evidence_recall():
    sources = [{"content": "Revenue increased and free cash flow was positive.", "metadata": {"source_type": "text", "page": ""}}]
    result = evaluate_retrieval("cash flow", sources, ["Revenue", "free cash flow"])
    assert result["passed"]
    assert result["expected_source_recall"] == 1.0


def test_local_file_index_infers_aapl_ticker_and_search_filters_by_ticker(tmp_path: Path):
    knowledge = tmp_path / "knowledge"
    knowledge.mkdir()
    (knowledge / "Apple_cash_flow_note.md").write_text("Apple free cash flow note", encoding="utf-8")
    (knowledge / "600519_cash_flow_note.md").write_text("Kweichow Moutai cash flow note", encoding="utf-8")

    rag = LocalResearchRAG(path=tmp_path / "chroma")
    rag.index_local_documents(knowledge)

    aapl_sources = rag.search("cash flow", ticker="AAPL")
    assert aapl_sources
    assert all(source["metadata"]["ticker"] == "AAPL" for source in aapl_sources)
    assert rag.search("cash flow", ticker="600519.SS")
    assert rag.search("cash flow", ticker="0700.HK") == []


def test_filename_ticker_inference_uses_known_aliases_and_unknown_without_guessing():
    assert infer_ticker_from_filename(Path("Apple_2025_Form_10-K.pdf")) == "AAPL"
    assert infer_ticker_from_filename(Path("600519_annual_report.pdf")) == "600519.SS"
    assert infer_ticker_from_filename(Path("sector_research.pdf")) == "unknown"



def test_financial_term_mapping_expands_chinese_query_with_reviewable_english_variants():
    expanded = expand_financial_query("Apple \u670d\u52a1\u4e1a\u52a1\u6536\u5165\u548c\u7814\u53d1\u8d39\u7528\u662f\u591a\u5c11\uff1f")
    assert "Services net sales" in expanded
    assert "Research and development" in expanded


def test_same_pdf_page_prefers_chunk_with_question_anchor(tmp_path: Path):
    class FakeCollection:
        def count(self):
            return 2

        def get(self, **kwargs):
            return {"ids": ["one", "two"]}

        def query(self, **kwargs):
            metadata = {"source_type": "pdf", "source_id": "annual-report-page-36", "page": "36"}
            return {
                "documents": [[
                    "Consolidated Statements of Cash Flows table heading.",
                    "Cash generated by operating activities was 111,482 in 2025.",
                ]],
                "metadatas": [[metadata, metadata]],
                "distances": [[0.1, 0.2]],
            }

    rag = LocalResearchRAG(path=tmp_path / "chroma")
    rag.collection = FakeCollection()
    rag.provider.embed = lambda values: [[0.0]]

    result = rag.search("Apple \u7ecf\u8425\u6d3b\u52a8\u4ea7\u751f\u7684\u73b0\u91d1 111,482", limit=1)

    assert len(result) == 1
    assert "111,482" in result[0]["content"]


def test_cross_encoder_unavailable_records_explicit_fallback(monkeypatch, tmp_path: Path):
    import sentence_transformers

    class UnavailableCrossEncoder:
        def __init__(self, *args, **kwargs):
            raise OSError("local model missing")

    monkeypatch.setenv("RAG_RERANKER_MODE", "cross_encoder")
    monkeypatch.setattr(sentence_transformers, "CrossEncoder", UnavailableCrossEncoder)
    rag = LocalResearchRAG(path=tmp_path / "chroma")

    status = rag.retrieval_status()

    assert status["reranker_mode"] == "hybrid_fallback"
    assert "Cross-Encoder" in status["reranker_fallback_reason"]
