"""R3 v2 gold discovery: 在给定的 4 份 PDF 中，用候选指标短语定位页码并抽取上下文片段，
用于逐页标注新的独立 holdout 金标准页（先于任何检索）。本脚本只为人工标注提供证据，不写交付物。
"""
from __future__ import annotations

from pathlib import Path

from pypdf import PdfReader

KB = Path(__file__).resolve().parent.parent / "data" / "knowledge_base"

PDFS = {
    "600519.SS": "600519_2025_annual_report.pdf",
    "AAPL": "Apple_2025_Form_10-K.pdf",
    "MSFT": "MSFT_SEC_10-K_2026-06-30_official-html.pdf",
    "0700.HK": "0700HK_annual_report_2025.pdf",
}

# 候选指标短语（均非 R0 已用事实）。Moutai 用中文；其余用英文。
CANDIDATES = {
    "600519.SS": [
        "应收账款", "预付款项", "其他应收款", "固定资产", "在建工程", "无形资产", "商誉",
        "短期借款", "长期借款", "应付债券", "股本", "资本公积", "盈余公积", "未分配利润",
        "稀释每股收益", "财务费用", "投资收益", "所得税费用", "营业税金及附加",
        "茅台酒", "系列酒", "国外", "经销商", "员工", "研发投入", "投资活动产生的现金流量净额",
        "筹资活动产生的现金流量净额", "购建固定资产",
    ],
    "AAPL": [
        "iPhone", "Mac", "iPad", "Services net sales", "Gross margin", "Net income",
        "Total net sales", "Operating income", "Provision for income taxes",
        "Cash and cash equivalents", "Marketable securities", "Total current assets",
        "Total liabilities", "Long-term debt", "Total shareholders", "Diluted earnings per share",
        "Cash generated by operating", "Research and development",
    ],
    "MSFT": [
        "Income before income taxes", "Provision for income taxes", "Cash and cash equivalents",
        "Total current assets", "Long-term debt", "Total stockholders", "Depreciation",
        "Amortization", "Capital expenditures", "Dividends", "Diluted earnings per share",
        "Commercial", "Product", "Service revenue", "Cash generated by operating",
    ],
    "0700.HK": [
        "Operating profit", "EBITDA", "Research and development", "Finance costs",
        "Income tax", "Cash and cash equivalents", "Total assets", "Total liabilities",
        "Equity", "Non-IFRS", "Gross margin", "Games", "Fintech", "Cloud", "Advertising",
        "Dividend",
    ],
}


def snippet(text: str, phrase: str, width: int = 200) -> str:
    idx = text.find(phrase)
    if idx < 0:
        return "<<NOT FOUND>>"
    s = max(0, idx - 30)
    e = min(len(text), idx + len(phrase) + width)
    return text[s:e].replace("\n", " ").strip()


def main() -> int:
    for ticker, fname in PDFS.items():
        path = KB / fname
        reader = PdfReader(str(path))
        pages = [p.extract_text() or "" for p in reader.pages]
        print(f"\n========== {ticker} [{fname}] pages={len(pages)} ==========", flush=True)
        for phrase in CANDIDATES[ticker]:
            hits = []
            for i, text in enumerate(pages, start=1):
                if phrase in text:
                    hits.append(i)
            if not hits:
                print(f"  {phrase!r}: NOT FOUND", flush=True)
                continue
            first = hits[0]
            print(f"  {phrase!r}: pages={hits[:6]} -> {snippet(pages[first-1], phrase)}", flush=True)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
